export const ADD_WORKOUT_RUN = "ADD_WORKOUT_RUN";
export const DELETE_WORKOUT_RUN = "DELETE_WORKOUT_RUN";
export const CHANGE_WORKOUT_RUN = "CHANGE_WORKOUT_RUN";
export const FILTER_WORKOUT_RUN = "FILTER_WORKOUT_RUN";